apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 03-redis.yaml
  - 04-backend.yaml
  - 05-frontend.yaml
  - 06-cleaner.yaml

configMapGenerator:
  - name: backend-config
    literals:
      - LOG_LEVEL=INFO
