apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cleaner
  labels:
    app: {{ .Release.Name }}-cleaner
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cleaner
            image: "{{ .Values.images.repoAccount }}/devops-news-cleaner:{{ .Values.images.tags.cleaner }}"
            imagePullPolicy: {{ .Values.images.pullPolicy }}
            env:
            - name: REDIS_HOST
              value: "{{ .Release.Name }}-redis"
            - name: REDIS_PASSWORD
              value: "{{ .Values.redis.password }}"
