name: Build and Push Docker Images

on:
  push:
    tags: ["v*"] # Déclenche le build uniquement lors d'un push de tag (ex: git push origin v1.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # On définit ici nos 3 services et leurs dossiers respectifs
        include:
          - image_name: devops-news-api
            context: ./src/backend
          - image_name: devops-news-front
            context: ./src/frontend
          - image_name: devops-news-cleaner
            context: ./src/cleaner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          # On tague l'image avec le tag git (ex: v1.0) et 'latest'
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest
          # Optimisation : utilise le cache de GitHub Actions pour accélérer les builds suivants
          cache-from: type=gha
          cache-to: type=gha,mode=max
